name: CICD Pipeline

on:
  push:
    branches:
      - main        # Trigger only on pushes to the 'main' branch

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --list 'v*-dev.*' --sort=-v:refname | head -n 1)
          [ -z "$latest_tag" ] && latest_tag="v1.0.0-dev.0"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Bump the dev version
        run: |
          base_tag=$(echo "$latest_tag" | cut -d'-' -f1)
          dev_number=$(echo "$latest_tag" | grep -oP '(?<=-dev\.)\d+')
          new_dev_number=$(( ${dev_number:-0} + 1 ))
          new_tag="${base_tag}-dev.${new_dev_number}"

          git tag $new_tag
          git push origin $new_tag  # ✅ Push with authentication

          echo "new_tag=$new_tag" >> $GITHUB_ENV

