name: CI

on:
  push:
    branches:
      - main        # Trigger only on pushes to the 'main' branch

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          # Get the latest tag matching the pattern v*-dev.*
          latest_tag=$(git tag --list 'v*-dev.*' --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Bump the dev version
        id: bump_tag
        run: |
          # Extract base version and dev number using shell tools
          base_tag=$(echo "$latest_tag" | cut -d'-' -f1)
          dev_number=$(echo "$latest_tag" | grep -oP '(?<=-dev\.)\d+')

          # Increment the dev number
          if [ -z "$dev_number" ]; then
            new_dev_number=0
          else
            new_dev_number=$((dev_number + 1))
          fi

          new_tag="${base_tag}-dev.${new_dev_number}"
          echo "New tag: $new_tag"

          # Configure Git and push the new tag
          git tag $new_tag
          git remote set-url origin https://iamro:${{ secrets.MY_GITHUB_PAT }}@github.com/${{ github.repository }}.git
          echo "Pushing tag"
          git push origin $new_tag


          echo "new_tag=$new_tag" >> $GITHUB_ENV
